version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432
  api:
    build: .
    command: npm run start
    depends_on:
      - postgres
